var establishments_data = [{
	'name': 'the station',
	'slogan':'the best place in the station',
	'sad': 20,
	'happy':'1k',
	'veryhappy': 50,
	'address': 'BRT Metropolitano, Cercado de Lima 15001',
	'schedule': '5am-11am',
	'web': 'www.thestation.com.pe',
	'delivery': '500 300 192',
	'latitude': '-12.0393264',
	'longitude': '-77.0433712',
	'logo': '../assets/images/',
	'image': 'url("../assets/images/pasta.jpg")',
	'price': '$$',
	'type': 'snacks',
	'district': 'cercado',
	'coment': '../assets/images/'
},
	{
	'name': 'al fresco',
	'slogan':'the greatest marine food',
	'sad': 5,
	'happy':'4k',
	'veryhappy': 90,
	'address': 'Malecón Balta 790, Miraflores LIMA 18',
	'schedule': '12am-11pm',
	'web': 'www.restorando.com.pe',
	'delivery': '(01) 2428960',
	'latitude': '-12.1242546',
	'longitude': '-77.033012',
	'logo': '../assets/images/',
	'image': 'url("../assets/images/chaufa.jpg")',
	'price': '$$$$',
	'type': 'marine-food',
	'district': 'miraflores',
	'coment': '../assets/images/'
},
	{
	'name': 'panchita',
	'slogan':'panchitas flavor',
	'sad': 18,
	'happy':'3k',
	'veryhappy': '1k',
	'address': 'Calle 2 de Mayo 298, Miraflores 15074',
	'schedule': '10am-11pm',
	'web': 'www.panchitaSazon.com.pe',
	'delivery': '(01) 2425957',
	'latitude': '-12.1178165',
	'longitude': '-77.03185839999999',
	'logo': '../assets/images/',
	'image': 'url("../assets/images/lomo.jpg")',
	'price': '$$$',
	'type': 'peruvian-food',
	'district': 'cercado de lima',
	'coment': '../assets/images/'
},
	{
	'name': 'arlotia',
	'slogan':'enjoy the moment',
	'sad': 12,
	'happy':'2.5k',
	'veryhappy': '1k',
	'address': 'Av. Almte. Miguel Grau 340, Barranco 15063',
	'schedule': '11am-11pm',
	'web': 'www.enjoyarlotia.com.pe',
	'delivery': '(01) 2562269',
	'latitude': '-12.1482122',
	'longitude': '-77.0211534',
	'logo': '../assets/images/',
	'image': 'url("../assets/images/marine-food.jpg")',
	'price': '$$$',
	'type': 'peruvian-food',
	'district': 'barranco',
	'coment': '../assets/images/'
},
	{
	'name': 'the 73',
	'slogan':'barranco\'s sun',
	'sad': 20,
	'happy':'2k',
	'veryhappy': '2k',
	'address': 'Av. El Sol 175, Barranco 15063',
	'schedule': '10m-12pm',
	'web': 'www.the73.com',
	'delivery': '(01) 2470780',
	'latitude': '-12.1396178',
	'longitude': '-77.0232994',
	'logo': '../assets/images/',
	'image': 'url("../assets/images/pizza2.jpg")',
	'price': '$$$',
	'type': 'peruvian-food',
	'district': 'barranco',
	'coment': '../assets/images/'
},
	{
	'name': 'sing frog',
	'slogan':'just sing',
	'sad': 60,
	'happy':'3k',
	'veryhappy': '4k',
	'address': 'Genova 101, Barranco 15063',
	'schedule': '1pm-1am',
	'web': 'www.singFrogperu.com',
	'delivery': '(01) 2477274',
	'latitude': '-12.1466626',
	'longitude': '-77.02223839999999',
	'logo': '../assets/images/',
	'image': 'url("../assets/images/roast-chicken.jpg")',
	'price': '$$$',
	'type': 'italian-food',
	'district': 'barranco'
},
	{
	'name': 'the road',
	'slogan':'meat lovers paradise',
	'sad': 10,
	'happy':'5k',
	'veryhappy': '2k',
	'address': 'Av. Rivera Navarrete 740, San Isidro 15046',
	'schedule': '9am-11pm',
	'web': 'www.the_road.pe',
	'delivery': '(01) 4422690',
	'latitude': '-12.094763',
	'longitude': '-77.02680579999999',
	'logo': '../assets/images/',
	'image': 'url("../assets/images/meat.jpg")',
	'price': '$$$',
	'type': 'meat',
	'district': 'san isidro'
},
	{
	'name': 'hanzo',
	'slogan':'japan is your home',
	'sad': '1k',
	'happy':'2M',
	'veryhappy': '1M',
	'address': 'Av. Los Conquistadores 598, San Isidro 15073',
	'schedule': '10am-11pm',
	'web': 'www.hanzo.com.pe',
	'delivery': '(01) 4226367',
	'latitude': '-12.1019139',
	'longitude': '-77.036845',
	'logo': '../assets/images/',
	'image': 'url("../assets/images/sushi.jpg")',
	'price': '$$$$',
	'type': 'japanese-food',
	'district': 'san isidro'
},
	{
	'name': 'pier41',
	'slogan':'all fresh',
	'sad': 99,
	'happy':'8k',
	'veryhappy': '3k',
	'address': 'Calle Francisco Masias 590, San Isidro 15046',
	'schedule': '9am-11pm',
	'web': 'www.pier41.pe',
	'delivery': ' (01) 4224129',
	'latitude': '-12.0926869',
	'longitude': '-77.0256924',
	'logo': '../assets/images/',
	'image': 'url("../assets/images/ceviche.jpg")',
	'price': '$$$',
	'type': 'marine-food',
	'district': 'san isidro'
},
	{
	'name': 'the rocoto',
	'slogan':'the the spicy touch',
	'sad': '1k',
	'happy':'8k',
	'veryhappy': '7k',
	'address': 'Av. Aviación 4907, Santiago de Surco 15038',
	'schedule': '9am-11pm',
	'web': 'www.rocotoTouch.pe',
	'delivery': '(01) 4483040',
	'latitude': '-12.1251081',
	'longitude': '-76.9992484',
	'logo': '../assets/images/',
	'image': 'url("../assets/images/lasagna.jpg")',
	'price': '$$',
	'type': 'lima-food',
	'district': 'surco'
},
  {
	'name': 'the torch',
	'slogan':'the cheesse light',
	'sad': 79,
	'happy':'3k',
	'veryhappy': '9k',
	'address': 'Av. Caminos del Inca 459, Santiago de Surco 15038',
	'schedule': '11am-10am',
	'web': 'www.thetorch.com.pe',
	'delivery': '(01) 3721376',
	'latitude': '-12.1150268',
	'longitude': '-76.9912255',
	'logo': '../assets/images/',
	'image': 'url("../assets/images/mini-pizza.jpg")',
	'price': '$$$',
	'type': 'italian-food',
	'district': 'surco'
},
	{
	'name': 'osaka',
	'slogan':'the japanese flavor',
	'sad': '1k',
	'happy':'9k',
	'veryhappy': '9k',
	'address': ' El Polo 660, Santiago de Surco 15023',
	'schedule': '12:30am-4pm',
	'web': 'www.osaka.pe',
	'delivery': '(01) 4377320',
	'latitude': '-12.1019395',
	'longitude': '-76.9714399',
	'logo': '../assets/images/',
	'image': 'url("../assets/images/roll-sushi.jpg")',
	'price': '$$$$',
	'type': 'japanese-food',
	'district': 'surco'
},
	{
	'name': 'the aguajal',
	'slogan':'from the jungle the food',
	'sad': 57,
	'happy':'4k',
	'veryhappy': '1k',
	'address': 'Jr. Huiracocha 1498 Jesús Maria, Cercado de Lima',
	'schedule': '8am-11pm',
	'web': 'www.theaguajal.com.pe',
	'delivery': '(01) 4319758',
	'latitude': '-12.0772486',
	'longitude': '-77.0487915',
	'logo': '../assets/images/',
	'image': 'url("../assets/images/jungle.jpg")',
	'price': '$$',
	'type': 'jungle-food',
	'district': 'cercado'
},
	{
	'name': 'two pirates',
	'slogan':'be a pirate',
	'sad': '1k',
	'happy':'3k',
	'veryhappy': '1k',
	'address': 'San Juan de Miraflores 15801',
	'schedule': '11am-11pm',
	'web': 'www.twopirates.com.pe',
	'delivery': '960 176 786',
	'latitude': '-12.1583342',
	'longitude': '-76.9729472',
	'logo': '../assets/images/',
	'image': 'url("../assets/images/chaufa2.jpg")',
	'price': '$$',
	'type': 'marine-food',
	'district': 'sanJuan'
},
	{
	'name': 'jumbo chifa',
	'slogan':'perunese food',
	'sad': 50,
	'happy':'1k',
	'veryhappy': '1k',
	'address': 'Av San Juan 785, San Juan de Miraflores 15801',
	'schedule': '11am-11pm',
	'web': 'www.jumboChifa.com.pe',
	'delivery': '(01) 4660683',
	'latitude': '-12.1604878',
	'longitude': '-76.9733945',
	'logo': '../assets/images/',
	'image': 'url("../assets/images/chinese-chicken.jpeg")',
	'price': '$',
	'type': 'peruvian-chinese food',
	'district': 'san juan de miraflores'
},
	{
	'name': 'tratoria DVito',
	'slogan':'your trattoria',
	'sad': 10,
	'happy':'7k',
	'veryhappy': '5k',
	'address': 'Martin Dulanto Street, Martin Dulanto 111, Miraflores Lima 18',
	'schedule': '8am-10pm',
	'web': 'www.trattoriaDonVito.com.pe',
	'delivery': '(01) 4458156',
	'latitude': '-12.1253428',
	'longitude': '-77.02187959999999',
	'logo': '../assets/images/',
	'image': 'url("../assets/images/tartelette.jpg")',
	'price': '$$$',
	'type': 'italian food',
	'district': 'miraflores'
},
	{
	'name': 'Tanta',
	'slogan':'tanta is your living room',
	'sad': '30',
	'happy':'1M',
	'veryhappy': '9k',
	'address': 'Av Vasco Núñez de Balboa 660, Miraflores 15074',
	'schedule': '11am-10pm',
	'web': 'www.tanta.com.pe',
	'delivery': '(01) 4445231',
	'latitude': '-12.1301948',
	'longitude': '-77.0245499',
	'logo': '../assets/images/',
	'image': 'url("../assets/images/tanta.jpg")',
	'price': '$$$$',
	'type': 'peruvian-food-gourmet',
	'district': 'miraflores'
},
	{
	'name': 'saqra',
	'slogan':'the sacred food',
	'sad': 71,
	'happy':'9k',
	'veryhappy': '1M',
	'address': 'Av. la Paz 646, Miraflores Lima 18',
	'schedule': '12am-12pm',
	'web': 'www.saqra.pe',
	'delivery': '500 300 192',
	'latitude': '-12.0393264',
	'longitude': '-77.0433712',
	'logo': '../assets/images/',
	'image': 'url("../assets/images/ham.jpg")',
	'price': '$$',
	'type': 'snacks',
	'district': 'miraflores'
},
	{
	'name': 'maido',
	'slogan':'delicious',
	'sad': 20,
	'happy':'3k',
	'veryhappy': '1k',
	'address': 'Calle San Martin 399, Miraflores 15074',
	'schedule': '5am-11am',
	'web': 'www.thestation.com.pe',
	'delivery': '(01) 4462512',
	'latitude': '-12.1254707',
	'longitude': '-77.0305827',
	'logo': '../assets/images/',
	'image': 'url("../assets/images/pavo.jpg")',
	'price': '$$$$',
	'type': 'peruvian-food',
	'district': 'miraflores'
},
	{
	'name': 'rafael',
	'slogan':'the true flavor',
	'sad': 10,
	'happy':'2k',
	'veryhappy': '1k',
	'address': 'Calle San Martin 300, Miraflores 15074',
	'schedule': '11am-11pm',
	'web': 'www.rafael_flavor.com',
	'delivery': '(01) 2424149',
	'latitude': '-12.1252575',
	'longitude': '-77.03139469999999',
	'logo': '../assets/images/',
	'image': 'url("../assets/images/potato-food.jpg")',
	'price': '$$$',
	'type': 'peruvian-food',
	'district': 'miraflores'
},
	{
	'name': 'wallqa',
	'slogan':'come and try peru',
	'sad': 4,
	'happy':'1k',
	'veryhappy': '1k',
	'address': 'Av Vasco Núñez de Balboa 530, Miraflores 15074',
	'schedule': '12am-12pm',
	'web': 'www.wallqa.com',
	'delivery': '(01) 2429619',
	'latitude': '-12.1312752',
	'longitude': '-77.0256254',
	'logo': '../assets/images/',
	'image': 'url("../assets/images/waffles.jpg")',
	'price': '$$$',
	'type': 'peruvian-food',
	'district': 'miraflores'
},
	{
	'name': 'buena vista',
	'slogan':'beauty and sight',
	'sad': 2,
	'happy':99,
	'veryhappy': '4k',
	'address': '15074, Malecón de la Marina 316, Miraflores 15074',
	'schedule': '1pm-12pm',
	'web': 'www.buenavistaCafe.com.pe',
	'delivery': '(01) 7240475',
	'latitude': '-12.1182765',
	'longitude': '-77.0454121',
	'logo': '../assets/images/',
	'image': 'url("../assets/images/coffee.jpg")',
	'price': '$$$',
	'type': 'coffee',
	'district': 'miraflores'
},
	{
	'name': 'donatello',
	'slogan':'the italian house',
	'sad': 14,
	'happy':'2k',
	'veryhappy': '1M',
	'address': ' Calle José Galvez 390, Miraflores 15074',
	'schedule': '12pm-11pm',
	'web': 'www.donatello.com.pe',
	'delivery': '(01) 4458047',
	'latitude': '-12.1212322',
	'longitude': '-77.0335968',
	'logo': '../assets/images/',
	'image': 'url("../assets/images/ensalada.jpg")',
	'price': '$$$',
	'type': 'italian-food',
	'district': 'miraflores'
}];